### ISSUE TITLE
mongo connection string heads up

### ISSUE THREAD

**Issue by Shrugs** [keonkim/bambooforest#1]
As a heads up, your mongo connection string is just chillin in your project here. I'd remove it and scrub your project's history (https://help.github.com/articles/remove-sensitive-data/). Instead compose your connection string with environment variables or a `super_secret_info.json` that's in your `.gitignore`.

Cheers.

**Comment by keonkim** [comment]
this code base is just to demo for English users, didn't have time to think about securities. 
I got real service going on here: https://github.com/keonkim/pook.
In it, I used local database connection without password, which strangely MongoDB promotes.
